print("demo'ing input")
name = input("What is your name?: ")
print(name)

print("input and math")
num1 = int(input("enter a number: "))
num2 = int(input("enter another number: "))
sum = (num1) + (num2)
print(sum)
print(f"The sum of {num1} and {num2} is {sum}")